# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 21) do

  create_table "affiliations", :force => true do |t|
    t.column "user_id",   :integer
    t.column "group_id",  :integer
    t.column "regular",   :boolean
    t.column "visitor",   :boolean
    t.column "presenter", :boolean
  end

  create_table "entries", :force => true do |t|
    t.column "date_published", :datetime
    t.column "authors",        :string
    t.column "content",        :text
    t.column "description",    :text
    t.column "title",          :string
    t.column "user_id",        :integer
  end

  create_table "facet_kinds", :force => true do |t|
    t.column "name",         :string,  :default => "", :null => false
    t.column "service_url",  :string
    t.column "title",        :string
    t.column "site",         :string
    t.column "feed",         :string
    t.column "aggregatable", :boolean
    t.column "favicon_url",  :string
  end

  create_table "facets", :force => true do |t|
    t.column "name",          :string
    t.column "info",          :string,  :default => "", :null => false
    t.column "user_id",       :integer,                 :null => false
    t.column "facet_kind_id", :integer,                 :null => false
  end

  create_table "groups", :force => true do |t|
    t.column "name",     :string,  :default => "", :null => false
    t.column "url",      :string
    t.column "once_off", :boolean
  end

  create_table "meetings", :force => true do |t|
    t.column "when",     :datetime,                 :null => false
    t.column "where",    :string,   :default => "", :null => false
    t.column "group_id", :integer
  end

  create_table "mugshots", :force => true do |t|
    t.column "size",         :integer
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "height",       :integer
    t.column "width",        :integer
    t.column "thumbnail",    :string
    t.column "parent_id",    :integer
  end

  add_index "mugshots", ["parent_id"], :name => "index_mugshots_on_parent_id"

  create_table "presentations", :force => true do |t|
    t.column "user_id",    :integer
    t.column "meeting_id", :integer
    t.column "title",      :string,  :default => "", :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "thankyous", :force => true do |t|
    t.column "reason",     :string
    t.column "source",     :string,   :limit => 8
    t.column "from_id",    :integer
    t.column "to_id",      :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "thankyous", ["from_id"], :name => "index_thankyous_on_from_id"
  add_index "thankyous", ["to_id"], :name => "index_thankyous_on_to_id"

  create_table "users", :force => true do |t|
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "mugshot_id",                :integer
    t.column "irc_nick",                  :string
    t.column "blurb",                     :string
    t.column "aliases",                   :string
    t.column "location",                  :string
    t.column "name",                      :string
    t.column "site_url",                  :string
    t.column "site_name",                 :string
    t.column "admin",                     :boolean,                :default => false
    t.column "working_at",                :string
    t.column "working_at_url",            :string
    t.column "working_on",                :string
    t.column "site_feed",                 :string
    t.column "site_feed_last_updated",    :datetime
    t.column "site_feed_title",           :string
    t.column "site_feed_desc",            :string
    t.column "alternate_irc_nick",        :string
  end

end
